package store.entity;
// Generated Dec 2, 2016 2:10:42 PM by Hibernate Tools 3.2.1.GA



/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private int id;
     private String type;
     private String name;
     private String description;
     private Integer customerid;

    public Product() {
    }

	
    public Product(int id) {
        this.id = id;
    }
    public Product(int id, String type, String name, String description, Integer customerid) {
       this.id = id;
       this.type = type;
       this.name = name;
       this.description = description;
       this.customerid = customerid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getCustomerid() {
        return this.customerid;
    }
    
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }




}


